# Generated by Django 3.2.19 on 2023-07-01 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('views', models.BigIntegerField(default=0)),
                ('content', djrichtextfield.models.RichTextField(max_length=15000)),
                ('journal_date', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField()),
                ('self_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[200, None], upload_to='self_images/')),
                ('day_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[800, None], upload_to='day_images/')),
                ('selected_theme', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
