# Generated by Django 3.2.19 on 2023-07-02 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-journal_date']},
        ),
        migrations.RemoveField(
            model_name='journal',
            name='selected_theme',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('account_activated', models.BooleanField(default=False)),
                ('make_new_page_public', models.BooleanField(default=False)),
                ('description_word_one', models.CharField(blank=True, max_length=50)),
                ('description_word_two', models.CharField(blank=True, max_length=50)),
                ('description_word_three', models.CharField(blank=True, max_length=50)),
                ('colour_theme', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
