# Generated by Django 4.2.2 on 2023-06-24 18:38

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_rename_date_journal_journal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='day_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[600, None], upload_to='self_images/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='self_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[200, None], upload_to='self_images/'),
        ),
    ]
