# Generated by Django 4.2.2 on 2023-06-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_journal_day_image_alter_journal_self_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='id',
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
