# Generated by Django 4.2.2 on 2023-06-25 09:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_remove_journal_journal_id_journal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='day_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[800, None], upload_to='day_images/'),
        ),
    ]
