# Generated by Django 3.2.19 on 2023-07-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_alter_journal_day_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
